server.port=8100
#actuator endpoint
management.endpoints.web.exposure.include=*

spring.cloud.config.server.git.uri=file:///C://Users//snistal//Desktop//Antra_Training//weather-config-repo
spring.cloud.config.server.git.default-label=main


